apiVersion: v1
kind: Service
metadata:
  name: javaimage-service
spec:
  selector:
    app: javaimage
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort
